/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mapaps1;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;


/**
 *
 * @author marin
 */
public class Sintomas extends javax.swing.JFrame {

    /**
     * Creates new form Sintomas
     */
    public Sintomas() {
        initComponents();      
        
      int pontos = 0;  
    }

    public int getPontos() {
        return pontos;
    }

    public void setPontos(int pontos) {
        this.pontos = pontos;
    }
    
    

    public JRadioButton getAglomeracao() {
        return aglomeracao;
    }

    public void setAgçomeracao(JRadioButton agçomeracao) {
        this.aglomeracao = agçomeracao;
    }

    public JRadioButton getCabeca() {
        return cabeca;
    }

    public void setCabeca(JRadioButton cabeca) {
        this.cabeca = cabeca;
    }

    public JRadioButton getCovid() {
        return covid;
    }

    public void setCovid(JRadioButton covid) {
        this.covid = covid;
    }

    public JRadioButton getDiarreia() {
        return diarreia;
    }

    public void setDiarreia(JRadioButton diarreia) {
        this.diarreia = diarreia;
    }

    public JRadioButton getDor() {
        return dor;
    }

    public void setDor(JRadioButton dor) {
        this.dor = dor;
    }

    public JRadioButton getFebre() {
        return febre;
    }

    public void setFebre(JRadioButton febre) {
        this.febre = febre;
    }

    public JRadioButton getGarganta() {
        return garganta;
    }

    public void setGarganta(JRadioButton garganta) {
        this.garganta = garganta;
    }

    public JRadioButton getNariz() {
        return nariz;
    }

    public void setNariz(JRadioButton nariz) {
        this.nariz = nariz;
    }

    public JButton getPronto() {
        return pronto;
    }

    public void setPronto(JButton pronto) {
        this.pronto = pronto;
    }

    public JRadioButton getRespiracao() {
        return respiracao;
    }

    public void setRespiracao(JRadioButton respiracao) {
        this.respiracao = respiracao;
    }

    public JRadioButton getTosse() {
        return tosse;
    }

    public void setTosse(JRadioButton tosse) {
        this.tosse = tosse;
    }

    public JButton getVoltar() {
        return voltar;
    }

    public void setVoltar(JButton voltar) {
        this.voltar = voltar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        febre = new javax.swing.JRadioButton();
        cabeca = new javax.swing.JRadioButton();
        pronto = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        nariz = new javax.swing.JRadioButton();
        garganta = new javax.swing.JRadioButton();
        tosse = new javax.swing.JRadioButton();
        respiracao = new javax.swing.JRadioButton();
        dor = new javax.swing.JRadioButton();
        diarreia = new javax.swing.JRadioButton();
        covid = new javax.swing.JRadioButton();
        aglomeracao = new javax.swing.JRadioButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        jLabel2.setText("Sintomas");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecione os seus sintomas abaixo");

        febre.setText("Febre");
        febre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                febreActionPerformed(evt);
            }
        });

        cabeca.setText("Dor de Cabeça");
        cabeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cabecaActionPerformed(evt);
            }
        });

        pronto.setText("Pronto");
        pronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prontoActionPerformed(evt);
            }
        });

        voltar.setText("voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        nariz.setText("Secreção nasal");
        nariz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narizActionPerformed(evt);
            }
        });

        garganta.setText("Dor de garganta");
        garganta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gargantaActionPerformed(evt);
            }
        });

        tosse.setText("Tosse seca");
        tosse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tosseActionPerformed(evt);
            }
        });

        respiracao.setText("Dificuldade respiratória");
        respiracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respiracaoActionPerformed(evt);
            }
        });

        dor.setText("Dores no corpo");
        dor.setToolTipText("");
        dor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dorActionPerformed(evt);
            }
        });

        diarreia.setText("Diarreia");
        diarreia.setToolTipText("");
        diarreia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diarreiaActionPerformed(evt);
            }
        });

        covid.setText("Contato com alguma pessao diagnosticada com COVID nos ultimos 14 dias");
        covid.setToolTipText("");
        covid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                covidActionPerformed(evt);
            }
        });

        aglomeracao.setText("Esteve em algum lugar com aglomeração");
        aglomeracao.setToolTipText("");
        aglomeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aglomeracaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pronto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(covid, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cabeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tosse, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(febre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dor, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nariz, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(garganta, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(respiracao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diarreia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(aglomeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(febre)
                    .addComponent(nariz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cabeca)
                    .addComponent(garganta))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respiracao)
                    .addComponent(tosse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dor)
                    .addComponent(diarreia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(covid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aglomeracao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pronto)
                    .addComponent(voltar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        Cadastro1 cd = new Cadastro1();
        cd.setVisible(true); 
        
    }//GEN-LAST:event_voltarActionPerformed

    private void febreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_febreActionPerformed
       pontos = pontos +5;
        
    }//GEN-LAST:event_febreActionPerformed

    private void prontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prontoActionPerformed
        BoasVindas1 bv = new BoasVindas1();
        if(pontos<10){
        JOptionPane.showMessageDialog(null,"Siga para ala de risco baixo, seus sintomas atingiram a pontuação: " +pontos);
        dispose();        
        bv.setVisible(true);
        }else if(pontos>=10 && pontos<20){
        JOptionPane.showMessageDialog(null,"Siga para ala de risco médio, seus sintomas atingiram a pontuação: " +pontos);
         dispose();        
        bv.setVisible(true);
    }else if(pontos>=20){
        JOptionPane.showMessageDialog(null,"Siga para ala de risco alto, seus sintomas atingiram a pontuação: " +pontos);
         dispose();        
        bv.setVisible(true);
    }else{
       JOptionPane.showMessageDialog(null,"Erro " +pontos); 
        dispose();        
        bv.setVisible(true);
    }
    }//GEN-LAST:event_prontoActionPerformed

    private void cabecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cabecaActionPerformed
        pontos = pontos +1;
    }//GEN-LAST:event_cabecaActionPerformed

    private void narizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narizActionPerformed
        pontos = pontos +1;
    }//GEN-LAST:event_narizActionPerformed

    private void gargantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gargantaActionPerformed
        pontos = pontos +1;
    }//GEN-LAST:event_gargantaActionPerformed

    private void tosseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tosseActionPerformed
        pontos = pontos +3;
    }//GEN-LAST:event_tosseActionPerformed

    private void respiracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respiracaoActionPerformed
        pontos = pontos +10;
    }//GEN-LAST:event_respiracaoActionPerformed

    private void dorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dorActionPerformed
        pontos = pontos +1;
    }//GEN-LAST:event_dorActionPerformed

    private void diarreiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diarreiaActionPerformed
        pontos = pontos +1;
    }//GEN-LAST:event_diarreiaActionPerformed

    private void covidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_covidActionPerformed
       pontos = pontos +10;
    }//GEN-LAST:event_covidActionPerformed

    private void aglomeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aglomeracaoActionPerformed
        pontos = pontos +3;
    }//GEN-LAST:event_aglomeracaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sintomas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aglomeracao;
    private javax.swing.JRadioButton cabeca;
    private javax.swing.JRadioButton covid;
    private javax.swing.JRadioButton diarreia;
    private javax.swing.JRadioButton dor;
    private javax.swing.JRadioButton febre;
    private javax.swing.JRadioButton garganta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton nariz;
    private javax.swing.JButton pronto;
    private javax.swing.JRadioButton respiracao;
    private javax.swing.JRadioButton tosse;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
    private int pontos;
}
